apiVersion: v1
kind: Service
metadata:
  name: mri-phen-api-service
spec:
  type: NodePort # Use LoadBalancer if running in a cloud provider
  selector:
    app: mri-phen-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
